name: Deploy to DonWeb

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy to DonWeb Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Clona el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Versión de Node.js compatible con tu app.

      - name: Install dependencies
        run: npm install  # Instala las dependencias de tu proyecto.

      - name: Build project
        run: npm run build  # Genera los archivos optimizados en el directorio "build".

      - name: Deploy to DonWeb via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}  # Dirección del servidor FTP.
          username: ${{ secrets.FTP_USERNAME }}  # Usuario.
          password: ${{ secrets.FTP_PASSWORD }}  # Contraseña.
          local-dir: build  # Carpeta local a subir (generada con npm run build).
          server-dir: /public_html  # Carpeta del servidor (ajústala según tu configuración).